runtime: java8

instance_class: F1

inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/partials)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/partials/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/test)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/test/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/admin)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/admin/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/jsp)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/jsp/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/worker)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/worker/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/auto)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/auto/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: always
- url: (/page)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: always
- url: (/page/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: always
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /partials
  script: unused
  login: optional
  secure: optional
- url: /partials/.*
  script: unused
  login: optional
  secure: optional
- url: /test
  script: unused
  login: admin
  secure: always
- url: /test/.*
  script: unused
  login: admin
  secure: always
- url: /admin
  script: unused
  login: admin
  secure: always
- url: /admin/.*
  script: unused
  login: admin
  secure: always
- url: /jsp
  script: unused
  login: admin
  secure: always
- url: /jsp/.*
  script: unused
  login: admin
  secure: always
- url: /worker
  script: unused
  login: admin
  secure: always
- url: /worker/.*
  script: unused
  login: admin
  secure: always
- url: /auto
  script: unused
  login: admin
  secure: always
- url: /auto/.*
  script: unused
  login: admin
  secure: always
- url: /page
  script: unused
  login: optional
  secure: always
- url: /page/.*
  script: unused
  login: optional
  secure: always
- url: /.*
  script: unused
  login: optional
  secure: optional
 skip_files: .git/
 